# Clock signal
set_property PACKAGE_PIN W5 [get_ports CLK_100MHZ]							
	set_property IOSTANDARD LVCMOS33 [get_ports CLK_100MHZ]
# LEDs
set_property PACKAGE_PIN U16 [get_ports led_debug_busy]					
	set_property IOSTANDARD LVCMOS33 [get_ports led_debug_busy]
#set_property PACKAGE_PIN E19 [get_ports {busy[1]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {busy[1]}]
#set_property PACKAGE_PIN U19 [get_ports {busy[2]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {busy[2]}]
#set_property PACKAGE_PIN V19 [get_ports {busy[3]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {busy[3]}]
#set_property PACKAGE_PIN W18 [get_ports {busy[4]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {busy[4]}]
#set_property PACKAGE_PIN U15 [get_ports {busy[5]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {busy[5]}]	
##Buttons
set_property PACKAGE_PIN U18 [get_ports {btn[0]}]						
	set_property IOSTANDARD LVCMOS33 [get_ports {btn[0]}]
set_property PACKAGE_PIN T18 [get_ports {btn[1]}]						
	set_property IOSTANDARD LVCMOS33 [get_ports {btn[1]}]
set_property PACKAGE_PIN W19 [get_ports {btn[3]}]						
	set_property IOSTANDARD LVCMOS33 [get_ports {btn[3]}]
set_property PACKAGE_PIN T17 [get_ports btn[2]]						
	set_property IOSTANDARD LVCMOS33 [get_ports btn[2]]
set_property PACKAGE_PIN U17 [get_ports btn[4]]						
	set_property IOSTANDARD LVCMOS33 [get_ports btn[4]]	
set_property PACKAGE_PIN A18 [get_ports tx]						
	set_property IOSTANDARD LVCMOS33 [get_ports tx]	

        	